"""v4 unified gstin first model core gst extraction

Revision ID: 23df76009888
Revises: 
Create Date: 2026-10-02 19:58:20.600237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23df76009888'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# (schema, type_name) — every PG enum used by the v4 model. Native enums are
# created by create_table's before_create event (memo'd once per type) and
# are NOT dropped by op.drop_table, so downgrade drops them explicitly.
ENUMS: list[tuple[str, str]] = [
    ('core', 'access_role'),
    ('core', 'filing_scheme'),
    ('extraction', 'capture_source'),
    ('extraction', 'job_status'),
    ('gst', 'amendment_status'),
    ('gst', 'export_pay_type'),
    ('gst', 'filing_status'),
    ('gst', 'gstr1_export_type'),
    ('gst', 'gstr2b_source'),
    ('gst', 'inv_typ'),
    ('gst', 'invoice_direction'),
    ('gst', 'invoice_status'),
    ('gst', 'match_status'),
    ('gst', 'note_status'),
    ('gst', 'note_type'),
    ('gst', 'series_doc_type'),
    ('gst', 'supply_type'),
]


def _drop_enums() -> None:
    from sqlalchemy.dialects.postgresql import ENUM

    bind = op.get_bind()
    for schema, name in ENUMS:
        enum_type = ENUM(name=name, schema=schema, create_type=False)
        enum_type.drop(bind, checkfirst=True)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gst_accounts',
    sa.Column('gstin', sa.String(length=15), nullable=False),
    sa.Column('pan', sa.String(length=10), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('trade_name', sa.String(length=255), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('filing_scheme', sa.Enum('REGULAR_MONTHLY', 'QRMP', 'COMPOSITION', name='filing_scheme', schema='core'), nullable=False),
    sa.Column('irn_applicable', sa.Boolean(), nullable=False),
    sa.Column('aato_latest_minor', sa.BigInteger(), nullable=False),
    sa.Column('registered_address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('gstin', name=op.f('pk_gst_accounts')),
    schema='core'
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('mobile', sa.String(length=15), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('mobile', name=op.f('uq_users_mobile')),
    schema='core'
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('payload_diff', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['core.users.id'], name=op.f('fk_audit_logs_actor_user_id_users')),
    sa.ForeignKeyConstraint(['gstin'], ['core.gst_accounts.gstin'], name=op.f('fk_audit_logs_gstin_gst_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs')),
    schema='core'
    )
    op.create_index('ix_audit_logs_at', 'audit_logs', ['at'], unique=False, schema='core')
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity', 'entity_id'], unique=False, schema='core')
    op.create_table('user_gst_access',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'FILER', 'VIEWER', name='access_role', schema='core'), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gstin'], ['core.gst_accounts.gstin'], name=op.f('fk_user_gst_access_gstin_gst_accounts')),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], name=op.f('fk_user_gst_access_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_gst_access')),
    sa.UniqueConstraint('user_id', 'gstin', name='uq_user_gst_access_user_gstin'),
    schema='core'
    )
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=False),
    sa.Column('fp', sa.String(length=6), nullable=False),
    sa.Column('capture_source', sa.Enum('PDF_SCAN', 'DIGITAL', 'PHOTO', 'WHATSAPP', name='capture_source', schema='extraction'), nullable=False),
    sa.Column('doc_type', sa.String(length=16), nullable=False),
    sa.Column('minio_key', sa.String(length=512), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gstin'], ['core.gst_accounts.gstin'], name=op.f('fk_documents_gstin_gst_accounts')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['core.users.id'], name=op.f('fk_documents_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    schema='extraction'
    )
    op.create_index('ix_documents_gstin_fp', 'documents', ['gstin', 'fp'], unique=False, schema='extraction')
    op.create_index('ix_documents_sha256', 'documents', ['sha256'], unique=False, schema='extraction')
    op.create_table('document_series',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=False),
    sa.Column('doc_type', sa.Enum('INV', 'CDN', 'DBN', name='series_doc_type', schema='gst'), nullable=False),
    sa.Column('series_code', sa.String(length=20), nullable=False),
    sa.Column('fy', sa.String(length=7), nullable=False),
    sa.Column('current_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gstin'], ['core.gst_accounts.gstin'], name=op.f('fk_document_series_gstin_gst_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_series')),
    sa.UniqueConstraint('gstin', 'doc_type', 'series_code', 'fy', name='uq_document_series_gstin_type_code_fy'),
    schema='gst'
    )
    op.create_table('filing_periods',
    sa.Column('gstin', sa.String(length=15), nullable=False),
    sa.Column('fp', sa.String(length=6), nullable=False),
    sa.Column('scheme_snapshot', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'READY_FOR_FILING', 'FILED', name='filing_status', schema='gst'), nullable=False),
    sa.Column('gstr1_due_date', sa.Date(), nullable=True),
    sa.Column('gstr3b_due_date', sa.Date(), nullable=True),
    sa.Column('iff_eligible', sa.Boolean(), nullable=False),
    sa.Column('nil_return', sa.Boolean(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filed_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['filed_by'], ['core.users.id'], name=op.f('fk_filing_periods_filed_by_users')),
    sa.ForeignKeyConstraint(['gstin'], ['core.gst_accounts.gstin'], name=op.f('fk_filing_periods_gstin_gst_accounts')),
    sa.PrimaryKeyConstraint('gstin', 'fp', name=op.f('pk_filing_periods')),
    schema='gst'
    )
    op.create_table('gstr1_exports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=False),
    sa.Column('fp', sa.String(length=6), nullable=False),
    sa.Column('generated_by', sa.Uuid(), nullable=True),
    sa.Column('json_minio_key', sa.String(length=512), nullable=False),
    sa.Column('invoice_count', sa.Integer(), nullable=False),
    sa.Column('totals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('export_type', sa.Enum('ORIGINAL', 'AMENDMENT', name='gstr1_export_type', schema='gst'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['core.users.id'], name=op.f('fk_gstr1_exports_generated_by_users')),
    sa.ForeignKeyConstraint(['gstin'], ['core.gst_accounts.gstin'], name=op.f('fk_gstr1_exports_gstin_gst_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gstr1_exports')),
    schema='gst'
    )
    op.create_index('ix_gstr1_exports_gstin_fp', 'gstr1_exports', ['gstin', 'fp'], unique=False, schema='gst')
    op.create_table('gstr2b_statements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=False),
    sa.Column('fp', sa.String(length=6), nullable=False),
    sa.Column('source', sa.Enum('PORTAL_UPLOAD', 'GSP_API', name='gstr2b_source', schema='gst'), nullable=False),
    sa.Column('raw_minio_key', sa.String(length=512), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('imported_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['gstin'], ['core.gst_accounts.gstin'], name=op.f('fk_gstr2b_statements_gstin_gst_accounts')),
    sa.ForeignKeyConstraint(['imported_by'], ['core.users.id'], name=op.f('fk_gstr2b_statements_imported_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gstr2b_statements')),
    sa.UniqueConstraint('gstin', 'fp', name='uq_gstr2b_statements_gstin_fp'),
    schema='gst'
    )
    op.create_table('gstr3b_exports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=False),
    sa.Column('fp', sa.String(length=6), nullable=False),
    sa.Column('auto_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('manual_overrides', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_by', sa.Uuid(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['core.users.id'], name=op.f('fk_gstr3b_exports_generated_by_users')),
    sa.ForeignKeyConstraint(['gstin'], ['core.gst_accounts.gstin'], name=op.f('fk_gstr3b_exports_gstin_gst_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gstr3b_exports')),
    sa.UniqueConstraint('gstin', 'fp', name='uq_gstr3b_exports_gstin_fp'),
    schema='gst'
    )
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gstin'], ['core.gst_accounts.gstin'], name=op.f('fk_notifications_gstin_gst_accounts')),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    schema='gst'
    )
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False, schema='gst')
    op.create_table('extraction_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'PREPROCESS', 'OCR_RUNNING', 'LLM_RUNNING', 'EXTRACTED', 'FAILED', 'NEEDS_REVIEW', 'CONFIRMED', name='job_status', schema='extraction'), nullable=False),
    sa.Column('preproc_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ocr_text_ref', sa.String(length=512), nullable=True),
    sa.Column('raw_llm_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_model', sa.String(length=64), nullable=True),
    sa.Column('llm_tokens_in', sa.Integer(), nullable=True),
    sa.Column('llm_tokens_out', sa.Integer(), nullable=True),
    sa.Column('confidence_avg', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['extraction.documents.id'], name=op.f('fk_extraction_jobs_document_id_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extraction_jobs')),
    schema='extraction'
    )
    op.create_index('ix_extraction_jobs_document', 'extraction_jobs', ['document_id'], unique=False, schema='extraction')
    op.create_index('ix_extraction_jobs_status', 'extraction_jobs', ['status'], unique=False, schema='extraction')
    op.create_table('gstr2b_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('statement_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_gstin', sa.String(length=15), nullable=False),
    sa.Column('invoice_no', sa.String(length=32), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('taxable_value_minor', sa.Integer(), nullable=False),
    sa.Column('cgst_minor', sa.Integer(), nullable=False),
    sa.Column('sgst_minor', sa.Integer(), nullable=False),
    sa.Column('igst_minor', sa.Integer(), nullable=False),
    sa.Column('cess_minor', sa.Integer(), nullable=False),
    sa.Column('itc_eligible', sa.Boolean(), nullable=False),
    sa.Column('doc_type', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['statement_id'], ['gst.gstr2b_statements.id'], name=op.f('fk_gstr2b_entries_statement_id_gstr2b_statements')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gstr2b_entries')),
    schema='gst'
    )
    op.create_index('ix_gstr2b_entries_statement', 'gstr2b_entries', ['statement_id'], unique=False, schema='gst')
    op.create_table('invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=False),
    sa.Column('fp', sa.String(length=6), nullable=False),
    sa.Column('direction', sa.Enum('SALES', 'PURCHASE', name='invoice_direction', schema='gst'), nullable=False),
    sa.Column('supplier_gstin', sa.String(length=15), nullable=True),
    sa.Column('buyer_gstin', sa.String(length=15), nullable=True),
    sa.Column('invoice_no', sa.String(length=32), nullable=False),
    sa.Column('series', sa.String(length=20), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('place_of_supply', sa.String(length=2), nullable=False),
    sa.Column('supply_type', sa.Enum('INTRA', 'INTER', name='supply_type', schema='gst'), nullable=False),
    sa.Column('rchrg', sa.Boolean(), nullable=False),
    sa.Column('inv_typ', sa.Enum('R', 'SEWP', 'SEWOP', 'DE', name='inv_typ', schema='gst'), nullable=False),
    sa.Column('export_pay_type', sa.Enum('WPAY', 'WOPAY', name='export_pay_type', schema='gst'), nullable=True),
    sa.Column('shipping_bill_no', sa.String(length=32), nullable=True),
    sa.Column('port_code', sa.String(length=10), nullable=True),
    sa.Column('total_value_minor', sa.Integer(), nullable=False),
    sa.Column('source_doc_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'LOCKED', name='invoice_status', schema='gst'), nullable=False),
    sa.Column('confirmed_by', sa.Uuid(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by'], ['core.users.id'], name=op.f('fk_invoices_confirmed_by_users')),
    sa.ForeignKeyConstraint(['gstin'], ['core.gst_accounts.gstin'], name=op.f('fk_invoices_gstin_gst_accounts')),
    sa.ForeignKeyConstraint(['source_doc_id'], ['extraction.documents.id'], name=op.f('fk_invoices_source_doc_id_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices')),
    sa.UniqueConstraint('gstin', 'fp', 'invoice_no', name='uq_invoices_gstin_fp_no'),
    schema='gst'
    )
    op.create_index('ix_invoices_gstin_fp', 'invoices', ['gstin', 'fp'], unique=False, schema='gst')
    op.create_table('invoice_drafts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('extraction_job_id', sa.Uuid(), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=False),
    sa.Column('fp', sa.String(length=6), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('field_confidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['extraction_job_id'], ['extraction.extraction_jobs.id'], name=op.f('fk_invoice_drafts_extraction_job_id_extraction_jobs')),
    sa.ForeignKeyConstraint(['gstin'], ['core.gst_accounts.gstin'], name=op.f('fk_invoice_drafts_gstin_gst_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_drafts')),
    schema='extraction'
    )
    op.create_index('ix_invoice_drafts_job', 'invoice_drafts', ['extraction_job_id'], unique=False, schema='extraction')
    op.create_table('credit_debit_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=False),
    sa.Column('fp', sa.String(length=6), nullable=False),
    sa.Column('note_type', sa.Enum('CDN', 'DBN', name='note_type', schema='gst'), nullable=False),
    sa.Column('reason_code', sa.String(length=16), nullable=False),
    sa.Column('source_invoice_id', sa.Uuid(), nullable=True),
    sa.Column('buyer_gstin', sa.String(length=15), nullable=True),
    sa.Column('party_name', sa.String(length=255), nullable=True),
    sa.Column('taxable_value_minor', sa.Integer(), nullable=False),
    sa.Column('cgst_minor', sa.Integer(), nullable=False),
    sa.Column('sgst_minor', sa.Integer(), nullable=False),
    sa.Column('igst_minor', sa.Integer(), nullable=False),
    sa.Column('cess_minor', sa.Integer(), nullable=False),
    sa.Column('series', sa.String(length=20), nullable=True),
    sa.Column('note_no', sa.String(length=32), nullable=False),
    sa.Column('note_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'LOCKED', name='note_status', schema='gst'), nullable=False),
    sa.Column('irn', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gstin'], ['core.gst_accounts.gstin'], name=op.f('fk_credit_debit_notes_gstin_gst_accounts')),
    sa.ForeignKeyConstraint(['source_invoice_id'], ['gst.invoices.id'], name=op.f('fk_credit_debit_notes_source_invoice_id_invoices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_debit_notes')),
    sa.UniqueConstraint('gstin', 'fp', 'note_no', name='uq_credit_debit_notes_gstin_fp_no'),
    schema='gst'
    )
    op.create_index('ix_credit_debit_notes_gstin_fp', 'credit_debit_notes', ['gstin', 'fp'], unique=False, schema='gst')
    op.create_table('e_invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('irn', sa.String(length=64), nullable=False),
    sa.Column('ack_no', sa.String(length=32), nullable=True),
    sa.Column('ack_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_qr_base64', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_window_until', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['gst.invoices.id'], name=op.f('fk_e_invoices_invoice_id_invoices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_e_invoices')),
    sa.UniqueConstraint('invoice_id', name=op.f('uq_e_invoices_invoice_id')),
    sa.UniqueConstraint('irn', name=op.f('uq_e_invoices_irn')),
    schema='gst'
    )
    op.create_table('invoice_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hsn_sac', sa.String(length=8), nullable=True),
    sa.Column('uqc', sa.String(length=3), nullable=True),
    sa.Column('qty', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('unit_price_minor', sa.Integer(), nullable=True),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('taxable_value_minor', sa.Integer(), nullable=False),
    sa.Column('cgst_minor', sa.Integer(), nullable=False),
    sa.Column('sgst_minor', sa.Integer(), nullable=False),
    sa.Column('igst_minor', sa.Integer(), nullable=False),
    sa.Column('cess_minor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['gst.invoices.id'], name=op.f('fk_invoice_lines_invoice_id_invoices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_lines')),
    sa.UniqueConstraint('invoice_id', 'line_no', name='uq_invoice_lines_inv_line'),
    schema='gst'
    )
    op.create_table('itc_reconciliation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=False),
    sa.Column('fp', sa.String(length=6), nullable=False),
    sa.Column('purchase_invoice_id', sa.Uuid(), nullable=True),
    sa.Column('gstr2b_entry_id', sa.Uuid(), nullable=True),
    sa.Column('match_status', sa.Enum('MATCHED', 'PROBABLE', 'UNMATCHED', 'MISSING_IN_2B', 'MISSING_IN_BOOKS', name='match_status', schema='gst'), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['gstin'], ['core.gst_accounts.gstin'], name=op.f('fk_itc_reconciliation_gstin_gst_accounts')),
    sa.ForeignKeyConstraint(['gstr2b_entry_id'], ['gst.gstr2b_entries.id'], name=op.f('fk_itc_reconciliation_gstr2b_entry_id_gstr2b_entries')),
    sa.ForeignKeyConstraint(['purchase_invoice_id'], ['gst.invoices.id'], name=op.f('fk_itc_reconciliation_purchase_invoice_id_invoices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_itc_reconciliation')),
    schema='gst'
    )
    op.create_index('ix_itc_reconciliation_gstin_fp', 'itc_reconciliation', ['gstin', 'fp'], unique=False, schema='gst')
    op.create_table('gstr1a_amendments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('target_export_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=True),
    sa.Column('cdn_id', sa.Uuid(), nullable=True),
    sa.Column('field_deltas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'EXPORTED', name='amendment_status', schema='gst'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exported_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cdn_id'], ['gst.credit_debit_notes.id'], name=op.f('fk_gstr1a_amendments_cdn_id_credit_debit_notes')),
    sa.ForeignKeyConstraint(['invoice_id'], ['gst.invoices.id'], name=op.f('fk_gstr1a_amendments_invoice_id_invoices')),
    sa.ForeignKeyConstraint(['target_export_id'], ['gst.gstr1_exports.id'], name=op.f('fk_gstr1a_amendments_target_export_id_gstr1_exports')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gstr1a_amendments')),
    schema='gst'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gstr1a_amendments', schema='gst')
    op.drop_index('ix_itc_reconciliation_gstin_fp', table_name='itc_reconciliation', schema='gst')
    op.drop_table('itc_reconciliation', schema='gst')
    op.drop_table('invoice_lines', schema='gst')
    op.drop_table('e_invoices', schema='gst')
    op.drop_index('ix_credit_debit_notes_gstin_fp', table_name='credit_debit_notes', schema='gst')
    op.drop_table('credit_debit_notes', schema='gst')
    op.drop_index('ix_invoice_drafts_job', table_name='invoice_drafts', schema='extraction')
    op.drop_table('invoice_drafts', schema='extraction')
    op.drop_index('ix_invoices_gstin_fp', table_name='invoices', schema='gst')
    op.drop_table('invoices', schema='gst')
    op.drop_index('ix_gstr2b_entries_statement', table_name='gstr2b_entries', schema='gst')
    op.drop_table('gstr2b_entries', schema='gst')
    op.drop_index('ix_extraction_jobs_status', table_name='extraction_jobs', schema='extraction')
    op.drop_index('ix_extraction_jobs_document', table_name='extraction_jobs', schema='extraction')
    op.drop_table('extraction_jobs', schema='extraction')
    op.drop_index('ix_notifications_user_created', table_name='notifications', schema='gst')
    op.drop_table('notifications', schema='gst')
    op.drop_table('gstr3b_exports', schema='gst')
    op.drop_table('gstr2b_statements', schema='gst')
    op.drop_index('ix_gstr1_exports_gstin_fp', table_name='gstr1_exports', schema='gst')
    op.drop_table('gstr1_exports', schema='gst')
    op.drop_table('filing_periods', schema='gst')
    op.drop_table('document_series', schema='gst')
    op.drop_index('ix_documents_sha256', table_name='documents', schema='extraction')
    op.drop_index('ix_documents_gstin_fp', table_name='documents', schema='extraction')
    op.drop_table('documents', schema='extraction')
    op.drop_table('user_gst_access', schema='core')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs', schema='core')
    op.drop_index('ix_audit_logs_at', table_name='audit_logs', schema='core')
    op.drop_table('audit_logs', schema='core')
    op.drop_table('users', schema='core')
    op.drop_table('gst_accounts', schema='core')
    _drop_enums()
    # ### end Alembic commands ###
