"""add core.dpdp_requests table

Revision ID: 86f8e79e7a13
Revises: a1c5e3f5005d
Create Date: 2026-10-06 12:17:39.046550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86f8e79e7a13'
down_revision: Union[str, Sequence[str], None] = 'a1c5e3f5005d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'dpdp_requests',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('gstin', sa.String(length=15), nullable=False),
        sa.Column(
            'request_type',
            sa.Enum(
                'EXPORT', 'ERASURE', name='dpdp_request_type', schema='core'
            ),
            nullable=False,
        ),
        sa.Column(
            'status',
            sa.Enum(
                'PENDING',
                'SLA_QUEUED',
                'COMPLETED',
                'FAILED',
                name='dpdp_request_status',
                schema='core',
            ),
            nullable=False,
        ),
        sa.Column(
            'retention_carve_out_applied', sa.Boolean(), nullable=False
        ),
        sa.Column('sla_due_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('payload', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_dpdp_requests')),
        schema='core',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dpdp_requests', schema='core')
    op.execute("DROP TYPE IF EXISTS core.dpdp_request_status CASCADE")
    op.execute("DROP TYPE IF EXISTS core.dpdp_request_type CASCADE")
    # ### end Alembic commands ###
