"""add deadline dates to filing_periods

Revision ID: a1c5e3f5005d
Revises: b31f7a20c9e4
Create Date: 2026-10-03 14:54:18.548666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'a1c5e3f5005d'
down_revision: Union[str, Sequence[str], None] = 'b31f7a20c9e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filing_periods', sa.Column('iff_due_date', sa.Date(), nullable=True), schema='gst')
    op.add_column('filing_periods', sa.Column('cmp08_due_date', sa.Date(), nullable=True), schema='gst')
    op.add_column('filing_periods', sa.Column('gstr4_due_date', sa.Date(), nullable=True), schema='gst')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filing_periods', 'iff_due_date', schema='gst')
    op.drop_column('filing_periods', 'cmp08_due_date', schema='gst')
    op.drop_column('filing_periods', 'gstr4_due_date', schema='gst')
    # ### end Alembic commands ###
